spring:
  application:
    name: jikmutest
  config:
    import:
      - optional:file:.env[.properties]

service:
  jwt:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    secret-key: ${JWT_SECRET_KEY}